name: CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Usar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Cache dependencias
        uses: actions/cache@v3
        with:
          path: ~/.npm # dónde guarda dependencias npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Instalar dependencias
        run: npm install

      - name: Scan de vulnerabilidades
        run: npm audit --audit-level=high

      - name: Correr pruebas
        run: npm test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: DeibyMoreno/test-git-actions

  docker-build:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Login DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build y push imagen
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/empresa-api:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/empresa-api:latest
